### ISSUE TITLE
error open() "/var/tmp/nginx/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream

### ISSUE THREAD

**Issue by insekticid** [php-earth/docker-php#9]
Hi, I found another problem when doing very long output, nginx will try to cache response via output buffer

but you got this error
`
open() "/var/tmp/nginx/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream
`

https://github.com/piwik/piwik/issues/11310#issuecomment-333145775

fixed it via 
`RUN chown -R www-data:www-data /var/tmp/nginx`

btw I am using your image as base for Piwik stats https://github.com/insekticid/docker-piwik/blob/master/Dockerfile

**Comment by petk** [comment]
Hello, I've checked this out and what might be better in this case is to run Nginx process as user and group `nginx` instead of the `www-data`... Alpine Linux has configured Nginx to run as `nginx` user and group and therefore sets these permissions on the mentioned temporary directory.

This is from the default `/etc/nginx/nginx.conf` on Alpine:
```nginxconf
user nginx;
# ...
```

I can reproduce the same issue if I manually set the user to `www-data` in nginx.conf. So that's why the permissions need to be adjusted manually also on that directory.

In case this is still problematic or I've missed something, let me know... Thanks for reporting :+1:
